### ISSUE TITLE
Cluster for integration test

### ISSUE THREAD

**Issue by ook** [kafkaex/kafka_ex#142]
Hi. I'm currently working on #120 and I'd like to setup a cluster that can pass integration tests.

I prepared a Docker image spawning 3 differents kafka brokers (classical id:0 on 9092 id1 on 9093 id 2 on 9094), they work well altogether (requests are balanced, no error). I don't understand why when I run the integration test I constantly get:

```
15:53:49.546 [error] Could not connect to broker "0.0.0.0":9093
15:53:49.547 [error] Could not connect to broker "0.0.0.0":9094
```
Have you some clue, or could you give me your setup?

Thanks

**Comment by bjhaid** [comment]
replace `"0.0.0.0"` with whatever IP address kafka running in the container is bound to in you config

**Comment by dantswain** [comment]
Docker + Kafka is a bit tricky.  Assuming you're using wurstmeister/kafka you'll need to set KAFKA_ADVERTISED_HOST.  This is my typical docker-compose kafka setup:

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181"
  kafka1:
    image: wurstmeister/kafka:0.9.0.1
    ports:
      - "9092"
    environment:
      KAFKA_CREATE_TOPICS: "${KAFKA_CREATE_TOPICS}"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: "${DOCKER_IP}"
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka:0.9.0.1
    ports:
      - "9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "${DOCKER_IP}"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: wurstmeister/kafka:0.9.0.1
    ports:
      - "9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "${DOCKER_IP}"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

You have to set `DOCKER_IP` and `KAFKA_CREATE_TOPICS` accordingly beforehand (you can probably just omit the `KAFKA_CREATE_TOPICS` line).  I use scripts to automate this :/

On a Mac you could do `ifconfig en0` and get the ip address of your machine and use that.  Then do something like

```
DOCKER_IP=10.0.1.1 docker-compose up -d
```
